jobs:
  - name: show-env
    plan:
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          run:
            path: printenv
          params:
            MANIFEST_FILE: manifest.yml
            artifactory_endpoint: ((artifactory_endpoint))
            artifactory_user: ((artifactory_user))

